version: '3.8'
services:
  bank-app:
    container_name: bank-app
    image: bank-app
    networks:
      - internal-network
    environment:
      - USER_DB=user
      - PASSWORD_DB=pruebas1
      - HOST=mysqldb
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    links:
      - mysqldb
    command:
      [
        './wait-for-mysqldb.sh',
        'mysqldb:3306',
        '-t',
        '6000',
        '--',
        'java',
        '-jar',
        './bank-app-0.0.1-SNAPSHOT.jar',
      ]
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    networks:
      - internal-network
    #command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=pruebas1
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pruebas1
      - MYSQL_DATABASE=app_bank
    volumes:
      - './data:/var/lib/mysql'
      - .docker/setup.sql:/bankApp/bdd/BaseDatos.sql
volumes:
  data:
networks:
  internal-network:
# docker exec -i mysqldb sh -c 'exec mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD"' < $PWD/script.sql